/**
 * Object storage contract for the presigned-upload flow:
 *
 * 1. The server validates the request and calls {@link StorageService.presignPut}.
 * 2. The browser PUTs the file directly to the returned URL.
 * 3. The server confirms with {@link StorageService.head} and sniffs magic bytes with
 *    {@link StorageService.getRange} before marking the media item as uploaded.
 * 4. Private objects are served via short-lived {@link StorageService.presignGet} URLs.
 *
 * The production implementation (WP-0.4) wraps Linode Object Storage via the
 * AWS S3 SDK; tests use `FakeStorage` from `apps/server/test/helpers/fakes.ts`.
 * Object keys are generated by the server, never taken from client input.
 */

/** Input for a presigned upload URL. */
export interface PresignPutInput {
  /** Server-generated object key, e.g. `cuencadas/2026/media/<uuid>.jpg`. */
  key: string;
  /** MIME type the client must send; bound into the signature. */
  contentType: string;
  /** Exact byte size the client declared; bound into the signature when supported. */
  contentLength: number;
  /** URL lifetime in seconds. Implementations apply a short default (e.g. 300). */
  expiresInSeconds?: number;
}

/**
 * Constraints baked into a presigned PUT's signature. These are enforced by
 * the storage provider, not set by the client. Browsers compute
 * `Content-Length` themselves (it is a forbidden request header), so the
 * declared size is enforced by signing it and sending the exact `File` body.
 * The post-upload `head()` size check is the backstop if the provider does
 * not enforce it.
 */
export interface SignedPutConstraints {
  contentType: string;
  contentLength: number;
}

/** A presigned upload the browser can perform without credentials. */
export interface PresignedPut {
  url: string;
  method: "PUT";
  /**
   * Headers the client must set itself, verbatim, for the signature to match:
   * `content-type` plus any `x-amz-*` headers (e.g. checksums). Never
   * includes forbidden headers such as `content-length`.
   */
  requiredHeaders: Record<string, string>;
  /** Server-side record of what was signed. Do not send it to the client as headers. */
  signed: SignedPutConstraints;
  expiresAt: Date;
}

/** Input for a presigned download URL. */
export interface PresignGetInput {
  key: string;
  /** URL lifetime in seconds. Implementations apply a short default (e.g. 300). */
  expiresInSeconds?: number;
  /** Optional `Content-Disposition` override, e.g. `attachment; filename="foto.jpg"`. */
  responseContentDisposition?: string;
}

/** A presigned, time-limited download URL. */
export interface PresignedGet {
  url: string;
  expiresAt: Date;
}

/** Metadata for a stored object. */
export interface ObjectHead {
  key: string;
  contentLength: number;
  contentType: string | null;
  etag: string | null;
  lastModified: Date | null;
}

/** Input for a direct server-side upload (e.g. generated thumbnails). */
export interface PutObjectInput {
  key: string;
  body: Uint8Array;
  contentType: string;
  /** Optional `Cache-Control` header for the stored object. */
  cacheControl?: string;
}

/** Object storage operations used by the API. */
export interface StorageService {
  /** Create a presigned PUT URL for a browser upload. */
  presignPut(input: PresignPutInput): Promise<PresignedPut>;
  /** Create a presigned GET URL for a private object. */
  presignGet(input: PresignGetInput): Promise<PresignedGet>;
  /** Return object metadata, or `null` if the object does not exist. */
  head(key: string): Promise<ObjectHead | null>;
  /**
   * Read bytes `[start, endInclusive]` of an object (HTTP Range semantics),
   * used to sniff magic bytes after an upload. Throws if the object is missing.
   * Returns fewer bytes when the object is shorter than the requested range.
   */
  getRange(key: string, start: number, endInclusive: number): Promise<Uint8Array>;
  /** Upload bytes from the server. Overwrites an existing object with the same key. */
  put(input: PutObjectInput): Promise<void>;
  /** Delete an object. Deleting a missing key is not an error. */
  delete(key: string): Promise<void>;
}
