-- Migration 0001 (WP-0.3). Generated by drizzle-kit, then hand-edited:
-- pre-steps that make existing rows satisfy the new constraints, renames that
-- keep data (item_date, item_time, display_order, room_type, photo_url) and
-- USING casts. The end state matches meta/0001_snapshot.json exactly.

-- Refuse to silently discard family data: the old user-keyed table is replaced
-- by people/person_relationships and has no automatic mapping. The drizzle
-- migrator runs all of 0001 in one transaction, so this RAISE rolls everything
-- back and leaves the database at 0000 (covered by migrations.test.ts).
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM "family_relationships") THEN
    RAISE EXCEPTION 'family_relationships has rows; migrate them to people/person_relationships by hand before 0001';
  END IF;
END $$;--> statement-breakpoint
-- profiles.user_id becomes NOT NULL UNIQUE: drop orphans, keep the newest profile per user.
DELETE FROM "profiles" WHERE "user_id" IS NULL;--> statement-breakpoint
DELETE FROM "profiles" AS "older" USING "profiles" AS "newer"
WHERE "older"."user_id" = "newer"."user_id"
  AND ("older"."updated_at", "older"."id") < ("newer"."updated_at", "newer"."id");--> statement-breakpoint
-- Pre-0001 sessions have no refresh tokens or idle/absolute expiry: everyone logs in again.
DELETE FROM "sessions";--> statement-breakpoint
-- Normalize emails so T1 lookups by lower(email) always match the stored value. Addresses
-- that differ only by case make users_email_lower_unique (below) fail, rolling back 0001.
UPDATE "users" SET "email" = lower(btrim("email")) WHERE "email" <> lower(btrim("email"));--> statement-breakpoint
UPDATE "cuencadas" SET "theme_color" = lower(btrim("theme_color"));--> statement-breakpoint
UPDATE "cuencadas" SET "theme_color" = '#0b5e55' WHERE "theme_color" !~ '^#[0-9a-f]{6}$';--> statement-breakpoint
UPDATE "cuencada_locations" SET "kind" = 'attraction' WHERE "kind" = 'map';--> statement-breakpoint
UPDATE "cuencada_locations" SET "kind" = 'other' WHERE "kind" NOT IN ('hotel', 'venue', 'attraction', 'other');--> statement-breakpoint
UPDATE "media_items" SET "moderation_status" = 'pending_review' WHERE "moderation_status" = 'pending';--> statement-breakpoint
UPDATE "media_items" SET "moderation_status" = 'hidden' WHERE "moderation_status" NOT IN ('pending_review', 'approved', 'hidden');--> statement-breakpoint
CREATE TABLE "refresh_tokens" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"session_id" uuid NOT NULL,
	"token_hash" text NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"used_at" timestamp with time zone,
	"replaced_by_token_id" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);--> statement-breakpoint
CREATE TABLE "chat_read_states" (
	"room_id" uuid NOT NULL,
	"user_id" uuid NOT NULL,
	"last_read_message_id" uuid,
	"last_read_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "chat_read_states_pkey" PRIMARY KEY("room_id","user_id")
);--> statement-breakpoint
CREATE TABLE "daily_messages" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"cuencada_id" uuid NOT NULL,
	"date" date NOT NULL,
	"message" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "daily_messages_message_length_check" CHECK (char_length("message") between 1 and 1000)
);--> statement-breakpoint
CREATE TABLE "media_reports" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"media_id" uuid NOT NULL,
	"reporter_user_id" uuid NOT NULL,
	"reason" text NOT NULL,
	"details" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "media_reports_reason_check" CHECK ("reason" in ('inappropriate', 'privacy', 'duplicate', 'other')),
	CONSTRAINT "media_reports_details_length_check" CHECK ("details" is null or char_length("details") <= 500)
);--> statement-breakpoint
CREATE TABLE "people" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid,
	"full_name" text NOT NULL,
	"nickname" text,
	"family_branch" text,
	"birth_year" integer,
	"death_year" integer,
	"deceased" boolean DEFAULT false NOT NULL,
	"created_by_user_id" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "people_birth_year_check" CHECK ("birth_year" is null or "birth_year" between 1800 and 2200),
	CONSTRAINT "people_death_year_check" CHECK ("death_year" is null or "death_year" between 1800 and 2200),
	CONSTRAINT "people_years_order_check" CHECK ("birth_year" is null or "death_year" is null or "death_year" >= "birth_year"),
	CONSTRAINT "people_death_implies_deceased_check" CHECK ("death_year" is null or "deceased")
);--> statement-breakpoint
CREATE TABLE "person_relationships" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"kind" text NOT NULL,
	"from_person_id" uuid NOT NULL,
	"to_person_id" uuid NOT NULL,
	"created_by_user_id" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "person_relationships_kind_check" CHECK ("kind" in ('parent_of', 'partner_of')),
	CONSTRAINT "person_relationships_no_self_check" CHECK ("from_person_id" <> "to_person_id")
);--> statement-breakpoint
CREATE TABLE "avatar_uploads" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"object_key" text NOT NULL,
	"mime_type" text NOT NULL,
	"byte_size" integer NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"confirmed_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "avatar_uploads_mime_type_check" CHECK ("mime_type" in ('image/jpeg', 'image/png', 'image/webp')),
	CONSTRAINT "avatar_uploads_byte_size_check" CHECK ("byte_size" > 0 and "byte_size" <= 10485760)
);--> statement-breakpoint
CREATE TABLE "cuencada_attendance" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"cuencada_id" uuid NOT NULL,
	"person_id" uuid NOT NULL,
	"created_by_user_id" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);--> statement-breakpoint
DROP TABLE "chat_participants" CASCADE;--> statement-breakpoint
DROP TABLE "family_relationships" CASCADE;--> statement-breakpoint
ALTER TABLE "audit_logs" ALTER COLUMN "metadata" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "audit_logs" ALTER COLUMN "metadata" SET DATA TYPE jsonb USING (
  CASE
    WHEN btrim("metadata") = '' THEN '{}'::jsonb
    WHEN jsonb_typeof("metadata"::jsonb) = 'object' THEN "metadata"::jsonb
    ELSE jsonb_build_object('legacy', "metadata"::jsonb)
  END
);--> statement-breakpoint
ALTER TABLE "audit_logs" ALTER COLUMN "metadata" SET DEFAULT '{}'::jsonb;--> statement-breakpoint
ALTER TABLE "chat_rooms" RENAME COLUMN "room_type" TO "kind";--> statement-breakpoint
UPDATE "chat_rooms" SET "kind" = CASE WHEN "cuencada_id" IS NULL THEN 'global' ELSE 'cuencada' END;--> statement-breakpoint
ALTER TABLE "cuencada_itinerary_items" RENAME COLUMN "item_date" TO "date";--> statement-breakpoint
-- ASSUMPTION: legacy item_date values were written as local Mérida midnight (or any
-- Mérida wall-clock time). A value written as UTC midnight (e.g. new Date("2026-09-13"))
-- would land on the PREVIOUS day here. No legacy itinerary rows exist (the scaffold never
-- wrote any), so do not reuse this cast for data stored as UTC dates.
ALTER TABLE "cuencada_itinerary_items" ALTER COLUMN "date" SET DATA TYPE date USING ("date" AT TIME ZONE 'America/Merida')::date;--> statement-breakpoint
ALTER TABLE "cuencada_itinerary_items" RENAME COLUMN "item_time" TO "start_time";--> statement-breakpoint
ALTER TABLE "cuencada_itinerary_items" ALTER COLUMN "start_time" SET DATA TYPE time USING (
  CASE
    WHEN btrim("start_time") ~ '^([01]?[0-9]|2[0-3]):[0-5][0-9](:[0-5][0-9])?$' THEN btrim("start_time")::time
    WHEN btrim("start_time") ~* '^(0?[1-9]|1[0-2]):[0-5][0-9] ?[ap]\.? ?m\.?$'
      THEN to_timestamp(upper(replace(replace(btrim("start_time"), '.', ''), ' ', '')), 'HH12:MIAM')::time
    ELSE NULL
  END
);--> statement-breakpoint
ALTER TABLE "cuencada_itinerary_items" RENAME COLUMN "display_order" TO "sort_order";--> statement-breakpoint
ALTER TABLE "cuencada_locations" RENAME COLUMN "display_order" TO "sort_order";--> statement-breakpoint
ALTER TABLE "media_items" ADD COLUMN "kind" text;--> statement-breakpoint
UPDATE "media_items" SET "kind" = CASE WHEN "mime_type" LIKE 'video/%' THEN 'video' ELSE 'image' END;--> statement-breakpoint
ALTER TABLE "media_items" ALTER COLUMN "kind" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "profiles" RENAME COLUMN "photo_url" TO "avatar_key";--> statement-breakpoint
ALTER TABLE "users" DROP CONSTRAINT "users_email_unique";--> statement-breakpoint
ALTER TABLE "announcements" DROP CONSTRAINT "announcements_created_by_user_id_users_id_fk";--> statement-breakpoint
ALTER TABLE "audit_logs" DROP CONSTRAINT "audit_logs_actor_user_id_users_id_fk";--> statement-breakpoint
ALTER TABLE "chat_messages" DROP CONSTRAINT "chat_messages_sender_user_id_users_id_fk";--> statement-breakpoint
ALTER TABLE "invites" DROP CONSTRAINT "invites_created_by_user_id_users_id_fk";--> statement-breakpoint
ALTER TABLE "media_items" DROP CONSTRAINT "media_items_uploaded_by_user_id_users_id_fk";--> statement-breakpoint
ALTER TABLE "cuencada_itinerary_items" ALTER COLUMN "description" SET DEFAULT '';--> statement-breakpoint
ALTER TABLE "media_items" ALTER COLUMN "moderation_status" SET DEFAULT 'approved';--> statement-breakpoint
ALTER TABLE "profiles" ALTER COLUMN "user_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "announcements" ADD COLUMN "pinned" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "announcements" ADD COLUMN "publish_at" timestamp with time zone DEFAULT now() NOT NULL;--> statement-breakpoint
ALTER TABLE "announcements" ADD COLUMN "expires_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "announcements" ADD COLUMN "updated_at" timestamp with time zone DEFAULT now() NOT NULL;--> statement-breakpoint
ALTER TABLE "audit_logs" ADD COLUMN "ip" text;--> statement-breakpoint
ALTER TABLE "chat_messages" ADD COLUMN "client_message_id" uuid;--> statement-breakpoint
ALTER TABLE "chat_messages" ADD COLUMN "deleted_by_user_id" uuid;--> statement-breakpoint
ALTER TABLE "cuencada_itinerary_items" ADD COLUMN "end_time" time;--> statement-breakpoint
ALTER TABLE "cuencada_itinerary_items" ADD COLUMN "location_id" uuid;--> statement-breakpoint
ALTER TABLE "cuencada_itinerary_items" ADD COLUMN "price_note" text;--> statement-breakpoint
ALTER TABLE "cuencada_itinerary_items" ADD COLUMN "created_at" timestamp with time zone DEFAULT now() NOT NULL;--> statement-breakpoint
ALTER TABLE "cuencada_itinerary_items" ADD COLUMN "updated_at" timestamp with time zone DEFAULT now() NOT NULL;--> statement-breakpoint
ALTER TABLE "cuencada_locations" ADD COLUMN "description" text;--> statement-breakpoint
ALTER TABLE "cuencada_locations" ADD COLUMN "maps_url" text;--> statement-breakpoint
ALTER TABLE "cuencada_locations" ADD COLUMN "lat" double precision;--> statement-breakpoint
ALTER TABLE "cuencada_locations" ADD COLUMN "lng" double precision;--> statement-breakpoint
ALTER TABLE "cuencada_locations" ADD COLUMN "visibility" text DEFAULT 'public' NOT NULL;--> statement-breakpoint
ALTER TABLE "cuencada_locations" ADD COLUMN "created_at" timestamp with time zone DEFAULT now() NOT NULL;--> statement-breakpoint
ALTER TABLE "cuencada_locations" ADD COLUMN "updated_at" timestamp with time zone DEFAULT now() NOT NULL;--> statement-breakpoint
ALTER TABLE "cuencada_rsvps" ADD COLUMN "arrival_date" date;--> statement-breakpoint
ALTER TABLE "cuencada_rsvps" ADD COLUMN "departure_date" date;--> statement-breakpoint
ALTER TABLE "cuencada_rsvps" ADD COLUMN "hotel_location_id" uuid;--> statement-breakpoint
ALTER TABLE "cuencadas" ADD COLUMN "timezone" text DEFAULT 'America/Merida' NOT NULL;--> statement-breakpoint
ALTER TABLE "cuencadas" ADD COLUMN "song_url" text;--> statement-breakpoint
ALTER TABLE "cuencadas" ADD COLUMN "whatsapp_url" text;--> statement-breakpoint
ALTER TABLE "cuencadas" ADD COLUMN "weather_widget_url" text;--> statement-breakpoint
ALTER TABLE "cuencadas" ADD COLUMN "external_album_url" text;--> statement-breakpoint
ALTER TABLE "cuencadas" ADD COLUMN "rsvp_deadline" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "invites" ADD COLUMN "display_name" text;--> statement-breakpoint
ALTER TABLE "invites" ADD COLUMN "person_id" uuid;--> statement-breakpoint
ALTER TABLE "invites" ADD COLUMN "note" text;--> statement-breakpoint
ALTER TABLE "invites" ADD COLUMN "revoked_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "invites" ADD COLUMN "last_sent_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "magic_links" ADD COLUMN "request_ip" text;--> statement-breakpoint
ALTER TABLE "media_items" ADD COLUMN "thumb_key" text;--> statement-breakpoint
ALTER TABLE "media_items" ADD COLUMN "display_key" text;--> statement-breakpoint
ALTER TABLE "media_items" ADD COLUMN "width" integer;--> statement-breakpoint
ALTER TABLE "media_items" ADD COLUMN "height" integer;--> statement-breakpoint
ALTER TABLE "media_items" ADD COLUMN "duration_seconds" integer;--> statement-breakpoint
ALTER TABLE "media_items" ADD COLUMN "upload_status" text DEFAULT 'pending_upload' NOT NULL;--> statement-breakpoint
ALTER TABLE "media_items" ADD COLUMN "upload_expires_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "media_items" ADD COLUMN "confirmed_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "media_items" ADD COLUMN "processed_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "media_items" ADD COLUMN "processing_error" text;--> statement-breakpoint
ALTER TABLE "media_items" ADD COLUMN "moderated_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "media_items" ADD COLUMN "moderated_by_user_id" uuid;--> statement-breakpoint
ALTER TABLE "media_items" ADD COLUMN "moderation_note" text;--> statement-breakpoint
ALTER TABLE "media_items" ADD COLUMN "deleted_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "media_items" ADD COLUMN "deleted_by_user_id" uuid;--> statement-breakpoint
ALTER TABLE "media_items" ADD COLUMN "updated_at" timestamp with time zone DEFAULT now() NOT NULL;--> statement-breakpoint
ALTER TABLE "profiles" ADD COLUMN "show_city" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "sessions" ADD COLUMN "last_used_at" timestamp with time zone DEFAULT now() NOT NULL;--> statement-breakpoint
ALTER TABLE "sessions" ADD COLUMN "idle_expires_at" timestamp with time zone NOT NULL;--> statement-breakpoint
ALTER TABLE "sessions" ADD COLUMN "absolute_expires_at" timestamp with time zone NOT NULL;--> statement-breakpoint
ALTER TABLE "sessions" ADD COLUMN "revoked_reason" text;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "email_verified_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "password_changed_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "invited_by_invite_id" uuid;--> statement-breakpoint
ALTER TABLE "refresh_tokens" ADD CONSTRAINT "refresh_tokens_session_id_sessions_id_fk" FOREIGN KEY ("session_id") REFERENCES "public"."sessions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "refresh_tokens" ADD CONSTRAINT "refresh_tokens_replaced_by_token_id_refresh_tokens_id_fk" FOREIGN KEY ("replaced_by_token_id") REFERENCES "public"."refresh_tokens"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chat_read_states" ADD CONSTRAINT "chat_read_states_room_id_chat_rooms_id_fk" FOREIGN KEY ("room_id") REFERENCES "public"."chat_rooms"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chat_read_states" ADD CONSTRAINT "chat_read_states_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chat_read_states" ADD CONSTRAINT "chat_read_states_last_read_message_id_chat_messages_id_fk" FOREIGN KEY ("last_read_message_id") REFERENCES "public"."chat_messages"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "daily_messages" ADD CONSTRAINT "daily_messages_cuencada_id_cuencadas_id_fk" FOREIGN KEY ("cuencada_id") REFERENCES "public"."cuencadas"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "media_reports" ADD CONSTRAINT "media_reports_media_id_media_items_id_fk" FOREIGN KEY ("media_id") REFERENCES "public"."media_items"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "media_reports" ADD CONSTRAINT "media_reports_reporter_user_id_users_id_fk" FOREIGN KEY ("reporter_user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "people" ADD CONSTRAINT "people_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "people" ADD CONSTRAINT "people_created_by_user_id_users_id_fk" FOREIGN KEY ("created_by_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "person_relationships" ADD CONSTRAINT "person_relationships_from_person_id_people_id_fk" FOREIGN KEY ("from_person_id") REFERENCES "public"."people"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "person_relationships" ADD CONSTRAINT "person_relationships_to_person_id_people_id_fk" FOREIGN KEY ("to_person_id") REFERENCES "public"."people"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "person_relationships" ADD CONSTRAINT "person_relationships_created_by_user_id_users_id_fk" FOREIGN KEY ("created_by_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "avatar_uploads" ADD CONSTRAINT "avatar_uploads_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cuencada_attendance" ADD CONSTRAINT "cuencada_attendance_cuencada_id_cuencadas_id_fk" FOREIGN KEY ("cuencada_id") REFERENCES "public"."cuencadas"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cuencada_attendance" ADD CONSTRAINT "cuencada_attendance_person_id_people_id_fk" FOREIGN KEY ("person_id") REFERENCES "public"."people"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cuencada_attendance" ADD CONSTRAINT "cuencada_attendance_created_by_user_id_users_id_fk" FOREIGN KEY ("created_by_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "refresh_tokens_token_hash_unique" ON "refresh_tokens" USING btree ("token_hash");--> statement-breakpoint
CREATE INDEX "refresh_tokens_session_id_idx" ON "refresh_tokens" USING btree ("session_id");--> statement-breakpoint
CREATE INDEX "refresh_tokens_replaced_by_token_id_idx" ON "refresh_tokens" USING btree ("replaced_by_token_id");--> statement-breakpoint
CREATE INDEX "chat_read_states_user_id_idx" ON "chat_read_states" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "chat_read_states_last_read_message_id_idx" ON "chat_read_states" USING btree ("last_read_message_id");--> statement-breakpoint
CREATE UNIQUE INDEX "daily_messages_cuencada_date_unique" ON "daily_messages" USING btree ("cuencada_id","date");--> statement-breakpoint
CREATE UNIQUE INDEX "media_reports_media_reporter_unique" ON "media_reports" USING btree ("media_id","reporter_user_id");--> statement-breakpoint
CREATE INDEX "media_reports_reporter_user_id_idx" ON "media_reports" USING btree ("reporter_user_id");--> statement-breakpoint
CREATE UNIQUE INDEX "people_user_id_unique" ON "people" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "people_created_by_user_id_idx" ON "people" USING btree ("created_by_user_id");--> statement-breakpoint
CREATE INDEX "people_full_name_lower_idx" ON "people" USING btree (lower("full_name"));--> statement-breakpoint
CREATE UNIQUE INDEX "person_relationships_kind_from_to_unique" ON "person_relationships" USING btree ("kind","from_person_id","to_person_id");--> statement-breakpoint
CREATE UNIQUE INDEX "person_relationships_partner_pair_unique" ON "person_relationships" USING btree (least("from_person_id", "to_person_id"),greatest("from_person_id", "to_person_id")) WHERE kind = 'partner_of';--> statement-breakpoint
CREATE INDEX "person_relationships_from_person_id_idx" ON "person_relationships" USING btree ("from_person_id");--> statement-breakpoint
CREATE INDEX "person_relationships_to_person_id_idx" ON "person_relationships" USING btree ("to_person_id");--> statement-breakpoint
CREATE INDEX "person_relationships_created_by_user_id_idx" ON "person_relationships" USING btree ("created_by_user_id");--> statement-breakpoint
CREATE UNIQUE INDEX "avatar_uploads_object_key_unique" ON "avatar_uploads" USING btree ("object_key");--> statement-breakpoint
CREATE INDEX "avatar_uploads_user_id_idx" ON "avatar_uploads" USING btree ("user_id");--> statement-breakpoint
CREATE UNIQUE INDEX "cuencada_attendance_cuencada_person_unique" ON "cuencada_attendance" USING btree ("cuencada_id","person_id");--> statement-breakpoint
CREATE INDEX "cuencada_attendance_person_id_idx" ON "cuencada_attendance" USING btree ("person_id");--> statement-breakpoint
CREATE INDEX "cuencada_attendance_created_by_user_id_idx" ON "cuencada_attendance" USING btree ("created_by_user_id");--> statement-breakpoint
ALTER TABLE "announcements" ADD CONSTRAINT "announcements_created_by_user_id_users_id_fk" FOREIGN KEY ("created_by_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "audit_logs" ADD CONSTRAINT "audit_logs_actor_user_id_users_id_fk" FOREIGN KEY ("actor_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chat_messages" ADD CONSTRAINT "chat_messages_deleted_by_user_id_users_id_fk" FOREIGN KEY ("deleted_by_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chat_messages" ADD CONSTRAINT "chat_messages_sender_user_id_users_id_fk" FOREIGN KEY ("sender_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cuencada_itinerary_items" ADD CONSTRAINT "cuencada_itinerary_items_location_id_cuencada_locations_id_fk" FOREIGN KEY ("location_id") REFERENCES "public"."cuencada_locations"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cuencada_rsvps" ADD CONSTRAINT "cuencada_rsvps_hotel_location_id_cuencada_locations_id_fk" FOREIGN KEY ("hotel_location_id") REFERENCES "public"."cuencada_locations"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "invites" ADD CONSTRAINT "invites_person_id_people_id_fk" FOREIGN KEY ("person_id") REFERENCES "public"."people"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "invites" ADD CONSTRAINT "invites_created_by_user_id_users_id_fk" FOREIGN KEY ("created_by_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "media_items" ADD CONSTRAINT "media_items_moderated_by_user_id_users_id_fk" FOREIGN KEY ("moderated_by_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "media_items" ADD CONSTRAINT "media_items_deleted_by_user_id_users_id_fk" FOREIGN KEY ("deleted_by_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "media_items" ADD CONSTRAINT "media_items_uploaded_by_user_id_users_id_fk" FOREIGN KEY ("uploaded_by_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "users" ADD CONSTRAINT "users_invited_by_invite_id_invites_id_fk" FOREIGN KEY ("invited_by_invite_id") REFERENCES "public"."invites"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "announcements_cuencada_publish_at_idx" ON "announcements" USING btree ("cuencada_id","publish_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "announcements_created_by_user_id_idx" ON "announcements" USING btree ("created_by_user_id");--> statement-breakpoint
CREATE INDEX "audit_logs_created_at_idx" ON "audit_logs" USING btree ("created_at" DESC NULLS LAST,"id" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "audit_logs_actor_created_at_idx" ON "audit_logs" USING btree ("actor_user_id","created_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "audit_logs_entity_idx" ON "audit_logs" USING btree ("entity_type","entity_id");--> statement-breakpoint
CREATE INDEX "audit_logs_action_idx" ON "audit_logs" USING btree ("action");--> statement-breakpoint
CREATE INDEX "chat_messages_room_keyset_idx" ON "chat_messages" USING btree ("room_id","created_at" DESC NULLS LAST,"id" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "chat_messages_sender_user_id_idx" ON "chat_messages" USING btree ("sender_user_id");--> statement-breakpoint
CREATE INDEX "chat_messages_deleted_by_user_id_idx" ON "chat_messages" USING btree ("deleted_by_user_id");--> statement-breakpoint
CREATE UNIQUE INDEX "chat_messages_sender_client_id_unique" ON "chat_messages" USING btree ("sender_user_id","client_message_id") WHERE client_message_id is not null;--> statement-breakpoint
CREATE UNIQUE INDEX "chat_rooms_global_unique" ON "chat_rooms" USING btree ("kind") WHERE kind = 'global';--> statement-breakpoint
CREATE UNIQUE INDEX "chat_rooms_cuencada_unique" ON "chat_rooms" USING btree ("cuencada_id") WHERE kind = 'cuencada';--> statement-breakpoint
CREATE INDEX "cuencada_itinerary_items_cuencada_date_sort_idx" ON "cuencada_itinerary_items" USING btree ("cuencada_id","date","sort_order");--> statement-breakpoint
CREATE INDEX "cuencada_itinerary_items_location_id_idx" ON "cuencada_itinerary_items" USING btree ("location_id");--> statement-breakpoint
CREATE INDEX "cuencada_locations_cuencada_sort_idx" ON "cuencada_locations" USING btree ("cuencada_id","sort_order");--> statement-breakpoint
CREATE INDEX "cuencada_rsvps_user_id_idx" ON "cuencada_rsvps" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "cuencada_rsvps_hotel_location_id_idx" ON "cuencada_rsvps" USING btree ("hotel_location_id");--> statement-breakpoint
CREATE INDEX "cuencadas_published_starts_at_idx" ON "cuencadas" USING btree ("is_published","starts_at");--> statement-breakpoint
CREATE UNIQUE INDEX "invites_token_hash_unique" ON "invites" USING btree ("token_hash");--> statement-breakpoint
CREATE INDEX "invites_created_by_user_id_idx" ON "invites" USING btree ("created_by_user_id");--> statement-breakpoint
CREATE INDEX "invites_person_id_idx" ON "invites" USING btree ("person_id");--> statement-breakpoint
CREATE INDEX "invites_status_created_at_idx" ON "invites" USING btree ("status","created_at");--> statement-breakpoint
CREATE UNIQUE INDEX "magic_links_token_hash_unique" ON "magic_links" USING btree ("token_hash");--> statement-breakpoint
CREATE INDEX "magic_links_user_id_idx" ON "magic_links" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "magic_links_email_created_at_idx" ON "magic_links" USING btree ("email","created_at");--> statement-breakpoint
CREATE UNIQUE INDEX "media_items_object_key_unique" ON "media_items" USING btree ("object_key");--> statement-breakpoint
CREATE INDEX "media_items_gallery_keyset_idx" ON "media_items" USING btree ("cuencada_id","created_at" DESC NULLS LAST,"id" DESC NULLS LAST) WHERE deleted_at is null;--> statement-breakpoint
CREATE INDEX "media_items_uploaded_by_user_id_idx" ON "media_items" USING btree ("uploaded_by_user_id");--> statement-breakpoint
CREATE INDEX "media_items_moderated_by_user_id_idx" ON "media_items" USING btree ("moderated_by_user_id");--> statement-breakpoint
CREATE INDEX "media_items_deleted_by_user_id_idx" ON "media_items" USING btree ("deleted_by_user_id");--> statement-breakpoint
CREATE INDEX "media_items_moderation_queue_idx" ON "media_items" USING btree ("moderation_status","upload_status","created_at");--> statement-breakpoint
CREATE UNIQUE INDEX "profiles_user_id_unique" ON "profiles" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "sessions_user_id_idx" ON "sessions" USING btree ("user_id");--> statement-breakpoint
CREATE UNIQUE INDEX "users_email_lower_unique" ON "users" USING btree (lower("email"));--> statement-breakpoint
CREATE INDEX "users_invited_by_invite_id_idx" ON "users" USING btree ("invited_by_invite_id");--> statement-breakpoint
ALTER TABLE "cuencadas" DROP COLUMN "status";--> statement-breakpoint
ALTER TABLE "media_items" DROP COLUMN "visibility";--> statement-breakpoint
ALTER TABLE "sessions" DROP COLUMN "refresh_token_hash";--> statement-breakpoint
ALTER TABLE "sessions" DROP COLUMN "expires_at";--> statement-breakpoint
ALTER TABLE "announcements" ADD CONSTRAINT "announcements_visibility_check" CHECK ("visibility" in ('public', 'members'));--> statement-breakpoint
ALTER TABLE "announcements" ADD CONSTRAINT "announcements_expiry_check" CHECK ("expires_at" is null or "expires_at" > "publish_at");--> statement-breakpoint
ALTER TABLE "audit_logs" ADD CONSTRAINT "audit_logs_metadata_object_check" CHECK (jsonb_typeof("metadata") = 'object');--> statement-breakpoint
ALTER TABLE "chat_messages" ADD CONSTRAINT "chat_messages_body_length_check" CHECK (char_length("body") between 1 and 2000);--> statement-breakpoint
ALTER TABLE "chat_rooms" ADD CONSTRAINT "chat_rooms_kind_check" CHECK ("kind" in ('global', 'cuencada'));--> statement-breakpoint
ALTER TABLE "chat_rooms" ADD CONSTRAINT "chat_rooms_kind_cuencada_check" CHECK (("kind" = 'global' and "cuencada_id" is null) or ("kind" = 'cuencada' and "cuencada_id" is not null));--> statement-breakpoint
ALTER TABLE "cuencada_itinerary_items" ADD CONSTRAINT "cuencada_itinerary_items_visibility_check" CHECK ("visibility" in ('public', 'members'));--> statement-breakpoint
ALTER TABLE "cuencada_itinerary_items" ADD CONSTRAINT "cuencada_itinerary_items_time_order_check" CHECK ("start_time" is null or "end_time" is null or "end_time" > "start_time");--> statement-breakpoint
ALTER TABLE "cuencada_locations" ADD CONSTRAINT "cuencada_locations_kind_check" CHECK ("kind" in ('hotel', 'venue', 'attraction', 'other'));--> statement-breakpoint
ALTER TABLE "cuencada_locations" ADD CONSTRAINT "cuencada_locations_visibility_check" CHECK ("visibility" in ('public', 'members'));--> statement-breakpoint
ALTER TABLE "cuencada_locations" ADD CONSTRAINT "cuencada_locations_lat_check" CHECK ("lat" is null or "lat" between -90 and 90);--> statement-breakpoint
ALTER TABLE "cuencada_locations" ADD CONSTRAINT "cuencada_locations_lng_check" CHECK ("lng" is null or "lng" between -180 and 180);--> statement-breakpoint
ALTER TABLE "cuencada_locations" ADD CONSTRAINT "cuencada_locations_lat_lng_pair_check" CHECK (("lat" is null) = ("lng" is null));--> statement-breakpoint
ALTER TABLE "cuencada_rsvps" ADD CONSTRAINT "cuencada_rsvps_status_check" CHECK ("status" in ('yes', 'maybe', 'no'));--> statement-breakpoint
ALTER TABLE "cuencada_rsvps" ADD CONSTRAINT "cuencada_rsvps_guest_count_check" CHECK ("guest_count" between 0 and 20);--> statement-breakpoint
ALTER TABLE "cuencada_rsvps" ADD CONSTRAINT "cuencada_rsvps_dates_check" CHECK ("arrival_date" is null or "departure_date" is null or "departure_date" >= "arrival_date");--> statement-breakpoint
ALTER TABLE "cuencada_rsvps" ADD CONSTRAINT "cuencada_rsvps_notes_length_check" CHECK ("notes" is null or char_length("notes") <= 500);--> statement-breakpoint
ALTER TABLE "cuencadas" ADD CONSTRAINT "cuencadas_year_check" CHECK ("year" between 1900 and 2200);--> statement-breakpoint
ALTER TABLE "cuencadas" ADD CONSTRAINT "cuencadas_dates_check" CHECK ("ends_at" > "starts_at");--> statement-breakpoint
ALTER TABLE "cuencadas" ADD CONSTRAINT "cuencadas_theme_color_check" CHECK ("theme_color" ~ '^#[0-9a-f]{6}$');--> statement-breakpoint
ALTER TABLE "invites" ADD CONSTRAINT "invites_role_check" CHECK ("role" in ('admin', 'member'));--> statement-breakpoint
ALTER TABLE "invites" ADD CONSTRAINT "invites_status_check" CHECK ("status" in ('pending', 'accepted', 'revoked', 'expired'));--> statement-breakpoint
ALTER TABLE "invites" ADD CONSTRAINT "invites_uses_check" CHECK ("max_uses" >= 1 and "use_count" >= 0 and "use_count" <= "max_uses");--> statement-breakpoint
ALTER TABLE "invites" ADD CONSTRAINT "invites_admin_bound_check" CHECK ("role" <> 'admin' or ("email" is not null and "max_uses" = 1));--> statement-breakpoint
ALTER TABLE "invites" ADD CONSTRAINT "invites_open_max_uses_check" CHECK ("email" is not null or "max_uses" <= 20);--> statement-breakpoint
ALTER TABLE "magic_links" ADD CONSTRAINT "magic_links_purpose_check" CHECK ("purpose" in ('login', 'password_reset', 'email_verify'));--> statement-breakpoint
ALTER TABLE "media_items" ADD CONSTRAINT "media_items_kind_check" CHECK ("kind" in ('image', 'video'));--> statement-breakpoint
ALTER TABLE "media_items" ADD CONSTRAINT "media_items_mime_type_check" CHECK ("mime_type" in ('image/jpeg', 'image/png', 'image/webp', 'video/mp4', 'video/quicktime'));--> statement-breakpoint
ALTER TABLE "media_items" ADD CONSTRAINT "media_items_upload_status_check" CHECK ("upload_status" in ('pending_upload', 'processing', 'ready', 'failed'));--> statement-breakpoint
ALTER TABLE "media_items" ADD CONSTRAINT "media_items_moderation_status_check" CHECK ("moderation_status" in ('pending_review', 'approved', 'hidden'));--> statement-breakpoint
ALTER TABLE "media_items" ADD CONSTRAINT "media_items_byte_size_check" CHECK ("byte_size" > 0 and "byte_size" <= 314572800);--> statement-breakpoint
ALTER TABLE "media_items" ADD CONSTRAINT "media_items_dimensions_check" CHECK (("width" is null or "width" > 0) and ("height" is null or "height" > 0) and ("duration_seconds" is null or "duration_seconds" >= 0));--> statement-breakpoint
ALTER TABLE "media_items" ADD CONSTRAINT "media_items_kind_mime_check" CHECK (("kind" = 'video') = ("mime_type" like 'video/%'));--> statement-breakpoint
ALTER TABLE "sessions" ADD CONSTRAINT "sessions_revoked_reason_check" CHECK ("revoked_reason" in ('logout', 'user_revoked', 'revoke_others', 'password_changed', 'password_reset', 'user_disabled', 'admin_revoked', 'refresh_reuse'));--> statement-breakpoint
ALTER TABLE "sessions" ADD CONSTRAINT "sessions_revoked_consistent_check" CHECK (("revoked_at" is null) = ("revoked_reason" is null));--> statement-breakpoint
ALTER TABLE "sessions" ADD CONSTRAINT "sessions_idle_before_absolute_check" CHECK ("idle_expires_at" <= "absolute_expires_at");--> statement-breakpoint
ALTER TABLE "users" ADD CONSTRAINT "users_role_check" CHECK ("role" in ('admin', 'member'));--> statement-breakpoint
ALTER TABLE "users" ADD CONSTRAINT "users_status_check" CHECK ("status" in ('active', 'disabled'));
