-- Migration 0002 (WP-2.1). EXPAND-ONLY: production applies it before the new
-- code goes live, so code built against 0001 must keep working on top of it.
-- Only nullable columns or columns with defaults, new constraints and one
-- widened CHECK; nothing is dropped, renamed or narrowed.
--
-- Generated by drizzle-kit, then hand-edited (the end state matches
-- meta/0002_snapshot.json):
--   * the composite FKs use `ON DELETE SET NULL (<column>)` (PG15+). Drizzle can
--     only express a plain SET NULL, which would also try to null the NOT NULL
--     cuencada_id. The snapshot records "set null"; drizzle-kit only diffs
--     schema against snapshot, so `generate` stays clean. Never `push` these.
--   * constraints are added NOT VALID and then validated, and in dependency
--     order (the unique target before the FKs that reference it);
--   * data steps: the first_published_at backfill and the repair of any
--     cross-Cuencada location references (the services already reject them,
--     so none are expected).

-- 1. profiles.listed_in_directory ("Aparecer en el directorio"). Constant
--    default, so this is a metadata-only change; every existing member stays listed.
ALTER TABLE "profiles" ADD COLUMN "listed_in_directory" boolean DEFAULT true NOT NULL;--> statement-breakpoint

-- 2. cuencadas.first_published_at, set on the first publish and never cleared.
ALTER TABLE "cuencadas" ADD COLUMN "first_published_at" timestamp with time zone;--> statement-breakpoint
-- Backfill: the real publish time was never recorded, so created_at stands in
-- (a lower bound, and stable across re-runs). "Was ever published" = published
-- now, or has its edition chat room, which T2 creates on first publish and which
-- survives unpublishing (the signal T2's delete guard used before this column).
UPDATE "cuencadas" SET "first_published_at" = "created_at"
WHERE "first_published_at" IS NULL
  AND ("is_published"
       OR EXISTS (SELECT 1 FROM "chat_rooms" WHERE "chat_rooms"."cuencada_id" = "cuencadas"."id"));--> statement-breakpoint

-- 3. cuencada_itinerary_items.tags. Per-tag trimming and 1–24 chars are
--    contract rules (a CHECK cannot iterate array elements without a function);
--    the DB caps the count and forbids NULL elements.
ALTER TABLE "cuencada_itinerary_items" ADD COLUMN "tags" text[] DEFAULT '{}'::text[] NOT NULL;--> statement-breakpoint
ALTER TABLE "cuencada_itinerary_items" ADD CONSTRAINT "cuencada_itinerary_items_tags_check" CHECK (cardinality("tags") <= 6 and array_position("tags", null) is null) NOT VALID;--> statement-breakpoint
ALTER TABLE "cuencada_itinerary_items" VALIDATE CONSTRAINT "cuencada_itinerary_items_tags_check";--> statement-breakpoint

-- 4. Same-Cuencada composite FKs. The existing single-column FKs on location_id
--    and hotel_location_id are kept (redundant but harmless; dropping them is a
--    later contract-phase cleanup, not an expand step).
ALTER TABLE "cuencada_locations" ADD CONSTRAINT "cuencada_locations_cuencada_id_id_unique" UNIQUE("cuencada_id","id");--> statement-breakpoint
-- Repair before validating: a reference to another edition's location is
-- already invalid for the services (400), so unlink it instead of failing.
UPDATE "cuencada_itinerary_items" AS "item" SET "location_id" = NULL, "updated_at" = now()
FROM "cuencada_locations" AS "location"
WHERE "item"."location_id" = "location"."id" AND "item"."cuencada_id" <> "location"."cuencada_id";--> statement-breakpoint
UPDATE "cuencada_rsvps" AS "rsvp" SET "hotel_location_id" = NULL, "updated_at" = now()
FROM "cuencada_locations" AS "location"
WHERE "rsvp"."hotel_location_id" = "location"."id" AND "rsvp"."cuencada_id" <> "location"."cuencada_id";--> statement-breakpoint
ALTER TABLE "cuencada_itinerary_items" ADD CONSTRAINT "cuencada_itinerary_items_location_same_cuencada_fk" FOREIGN KEY ("cuencada_id","location_id") REFERENCES "public"."cuencada_locations"("cuencada_id","id") ON DELETE SET NULL ("location_id") ON UPDATE no action NOT VALID;--> statement-breakpoint
ALTER TABLE "cuencada_itinerary_items" VALIDATE CONSTRAINT "cuencada_itinerary_items_location_same_cuencada_fk";--> statement-breakpoint
ALTER TABLE "cuencada_rsvps" ADD CONSTRAINT "cuencada_rsvps_hotel_same_cuencada_fk" FOREIGN KEY ("cuencada_id","hotel_location_id") REFERENCES "public"."cuencada_locations"("cuencada_id","id") ON DELETE SET NULL ("hotel_location_id") ON UPDATE no action NOT VALID;--> statement-breakpoint
ALTER TABLE "cuencada_rsvps" VALIDATE CONSTRAINT "cuencada_rsvps_hotel_same_cuencada_fk";--> statement-breakpoint

-- 5. sessions.revoked_reason gains 'logout_all'. Widening only: every existing
--    value stays allowed. Drop and re-add run in the migration's transaction,
--    so there is no window without the CHECK.
ALTER TABLE "sessions" DROP CONSTRAINT "sessions_revoked_reason_check";--> statement-breakpoint
ALTER TABLE "sessions" ADD CONSTRAINT "sessions_revoked_reason_check" CHECK ("revoked_reason" in ('logout', 'user_revoked', 'revoke_others', 'password_changed', 'password_reset', 'user_disabled', 'admin_revoked', 'refresh_reuse', 'logout_all')) NOT VALID;--> statement-breakpoint
ALTER TABLE "sessions" VALIDATE CONSTRAINT "sessions_revoked_reason_check";
