-- Migration 0003 (WP-3.1a): undated ("announced") editions. EXPAND-ONLY:
-- production applies it before the new code goes live, and code built against
-- 0002 keeps working on top of it, because only the new code ever writes a
-- NULL date or place. Existing rows are untouched (no data step).
--
-- Generated by drizzle-kit, then hand-edited (the end state matches
-- meta/0003_snapshot.json): comments, and the CHECK is added NOT VALID and then
-- validated, like 0002. The drizzle migrator runs the file in one transaction,
-- so there is no window without a dates CHECK.
--
-- Audit of what else assumed non-null dates (none needed a change):
--   * `year` is its own NOT NULL column with its own CHECK; nothing derives it
--     from `starts_at`.
--   * `cuencadas_published_starts_at_idx (is_published, starts_at)`: a btree
--     indexes NULLs; it stays.
--   * No FK, CHECK or index references `rsvp_deadline` together with the dates,
--     and no other table references `starts_at`/`ends_at`/`city`/`state`.

-- 1. Both dates or neither. The old CHECK (`ends_at > starts_at`) passed when a
--    date was NULL, so drop it before the columns accept NULLs.
ALTER TABLE "cuencadas" DROP CONSTRAINT "cuencadas_dates_check";--> statement-breakpoint
ALTER TABLE "cuencadas" ALTER COLUMN "starts_at" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "cuencadas" ALTER COLUMN "ends_at" DROP NOT NULL;--> statement-breakpoint
-- 2. The place can be undecided too, independently of the dates.
ALTER TABLE "cuencadas" ALTER COLUMN "city" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "cuencadas" ALTER COLUMN "state" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "cuencadas" ADD CONSTRAINT "cuencadas_dates_check" CHECK (("starts_at" is null and "ends_at" is null) or ("starts_at" is not null and "ends_at" is not null and "ends_at" > "starts_at")) NOT VALID;--> statement-breakpoint
ALTER TABLE "cuencadas" VALIDATE CONSTRAINT "cuencadas_dates_check";
