-- Migration 0004 (WP-4.0): family people details, tree photos, undo history
-- and directory contacts. EXPAND-ONLY: production applies it before the new
-- code goes live, and 0003-era code keeps working on top of it:
--   * every new column is nullable or has a constant default
--     (`contact_visibility '{}'`), so old inserts and updates are unaffected
--     and ADD COLUMN is metadata-only;
--   * the new CHECKs only constrain the new columns, which old code never
--     writes; nothing is dropped, renamed or narrowed;
--   * `profiles.phone` is NOT rewritten here: the contract gained an E.164
--     normalizer and a later WP backfills existing values.
--
-- Generated by drizzle-kit, then hand-edited (the end state matches
-- meta/0004_snapshot.json): comments, CHECKs and the FK on the existing
-- tables (`people`, `profiles`) are added NOT VALID and then validated, like
-- 0002/0003, and the table/column COMMENTs (drizzle has no syntax for them).
-- The drizzle migrator runs the file in one transaction.
--
-- The handle regexes are generated from CONTACT_HANDLE_RULES / E164_PATTERN in
-- packages/types/src/contacts.ts (single source of truth). Changing one needs
-- a new migration.

-- 1. New tables (empty: their constraints are created valid).
CREATE TABLE "person_photo_uploads" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"person_id" uuid NOT NULL,
	"uploaded_by_user_id" uuid,
	"object_key" text NOT NULL,
	"mime_type" text NOT NULL,
	"byte_size" integer NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"confirmed_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "person_photo_uploads_mime_type_check" CHECK ("mime_type" in ('image/jpeg', 'image/png', 'image/webp')),
	CONSTRAINT "person_photo_uploads_byte_size_check" CHECK ("byte_size" > 0 and "byte_size" <= 10485760)
);
--> statement-breakpoint
CREATE TABLE "person_revisions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"person_id" uuid,
	"relationship_id" uuid,
	"actor_user_id" uuid,
	"action" text NOT NULL,
	"before" jsonb,
	"after" jsonb,
	"reverted_by_revision_id" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "person_revisions_action_check" CHECK ("action" in ('person.create', 'person.update', 'person.delete', 'relationship.create', 'relationship.delete', 'person.photo', 'person.revert')),
	CONSTRAINT "person_revisions_snapshots_check" CHECK (("before" is null or (jsonb_typeof("before") = 'object' and coalesce(jsonb_typeof("before" -> 'personId'), '') = 'string')) and ("after" is null or (jsonb_typeof("after") = 'object' and coalesce(jsonb_typeof("after" -> 'personId'), '') = 'string'))),
	CONSTRAINT "person_revisions_has_snapshot_check" CHECK ("before" is not null or "after" is not null),
	CONSTRAINT "person_revisions_not_self_reverted_check" CHECK ("reverted_by_revision_id" is null or "reverted_by_revision_id" <> "id")
);
--> statement-breakpoint
COMMENT ON TABLE "person_revisions" IS 'WP-4.0 undo history of family edits. Contains PII (before/after snapshots: names, full dates, birthplace, bio). Admin-only reads; never copy into audit_logs. Retention: 1 year, deleted by a cleanup job (WP-4.1). Every snapshot carries personId so an admin can purge all history about a person on a removal request.';--> statement-breakpoint
COMMENT ON TABLE "person_photo_uploads" IS 'WP-4.0 pending tree-photo uploads (mirrors avatar_uploads). Photos of people without accounts are PII.';--> statement-breakpoint
ALTER TABLE "person_photo_uploads" ADD CONSTRAINT "person_photo_uploads_person_id_people_id_fk" FOREIGN KEY ("person_id") REFERENCES "public"."people"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "person_photo_uploads" ADD CONSTRAINT "person_photo_uploads_uploaded_by_user_id_users_id_fk" FOREIGN KEY ("uploaded_by_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "person_revisions" ADD CONSTRAINT "person_revisions_person_id_people_id_fk" FOREIGN KEY ("person_id") REFERENCES "public"."people"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "person_revisions" ADD CONSTRAINT "person_revisions_actor_user_id_users_id_fk" FOREIGN KEY ("actor_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "person_revisions" ADD CONSTRAINT "person_revisions_reverted_by_revision_id_person_revisions_id_fk" FOREIGN KEY ("reverted_by_revision_id") REFERENCES "public"."person_revisions"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "person_photo_uploads_object_key_unique" ON "person_photo_uploads" USING btree ("object_key");--> statement-breakpoint
CREATE INDEX "person_photo_uploads_person_id_idx" ON "person_photo_uploads" USING btree ("person_id");--> statement-breakpoint
CREATE INDEX "person_photo_uploads_uploaded_by_user_id_idx" ON "person_photo_uploads" USING btree ("uploaded_by_user_id");--> statement-breakpoint
CREATE INDEX "person_revisions_person_id_created_at_idx" ON "person_revisions" USING btree ("person_id","created_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "person_revisions_created_at_idx" ON "person_revisions" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "person_revisions_actor_user_id_idx" ON "person_revisions" USING btree ("actor_user_id");--> statement-breakpoint
CREATE INDEX "person_revisions_reverted_by_revision_id_idx" ON "person_revisions" USING btree ("reverted_by_revision_id") WHERE "reverted_by_revision_id" is not null;--> statement-breakpoint
-- 2. people: full dates, birthplace, bio, tree photo, last editor.
ALTER TABLE "people" ADD COLUMN "birth_date" date;--> statement-breakpoint
ALTER TABLE "people" ADD COLUMN "death_date" date;--> statement-breakpoint
ALTER TABLE "people" ADD COLUMN "birthplace" text;--> statement-breakpoint
ALTER TABLE "people" ADD COLUMN "bio" text;--> statement-breakpoint
ALTER TABLE "people" ADD COLUMN "photo_key" text;--> statement-breakpoint
ALTER TABLE "people" ADD COLUMN "photo_updated_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "people" ADD COLUMN "updated_by_user_id" uuid;--> statement-breakpoint
ALTER TABLE "people" ADD CONSTRAINT "people_updated_by_user_id_users_id_fk" FOREIGN KEY ("updated_by_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action NOT VALID;--> statement-breakpoint
ALTER TABLE "people" VALIDATE CONSTRAINT "people_updated_by_user_id_users_id_fk";--> statement-breakpoint
CREATE INDEX "people_updated_by_user_id_idx" ON "people" USING btree ("updated_by_user_id");--> statement-breakpoint
-- Date/year rule: the year columns stay; a full date requires its year and
-- must fall in it (the contract derives the year from the date). With that,
-- the existing year range and death-implies-deceased CHECKs cover the dates.
ALTER TABLE "people" ADD CONSTRAINT "people_birth_date_year_check" CHECK ("birth_date" is null or ("birth_year" is not null and extract(year from "birth_date") = "birth_year")) NOT VALID;--> statement-breakpoint
ALTER TABLE "people" ADD CONSTRAINT "people_death_date_year_check" CHECK ("death_date" is null or ("death_year" is not null and extract(year from "death_date") = "death_year")) NOT VALID;--> statement-breakpoint
ALTER TABLE "people" ADD CONSTRAINT "people_dates_order_check" CHECK ("birth_date" is null or "death_date" is null or "death_date" >= "birth_date") NOT VALID;--> statement-breakpoint
ALTER TABLE "people" ADD CONSTRAINT "people_birthplace_length_check" CHECK ("birthplace" is null or char_length("birthplace") <= 120) NOT VALID;--> statement-breakpoint
ALTER TABLE "people" ADD CONSTRAINT "people_bio_length_check" CHECK ("bio" is null or char_length("bio") <= 1000) NOT VALID;--> statement-breakpoint
ALTER TABLE "people" ADD CONSTRAINT "people_photo_check" CHECK ("photo_key" is null or "photo_updated_at" is not null) NOT VALID;--> statement-breakpoint
ALTER TABLE "people" VALIDATE CONSTRAINT "people_birth_date_year_check";--> statement-breakpoint
ALTER TABLE "people" VALIDATE CONSTRAINT "people_death_date_year_check";--> statement-breakpoint
ALTER TABLE "people" VALIDATE CONSTRAINT "people_dates_order_check";--> statement-breakpoint
ALTER TABLE "people" VALIDATE CONSTRAINT "people_birthplace_length_check";--> statement-breakpoint
ALTER TABLE "people" VALIDATE CONSTRAINT "people_bio_length_check";--> statement-breakpoint
ALTER TABLE "people" VALIDATE CONSTRAINT "people_photo_check";--> statement-breakpoint
-- 3. person_relationships: provenance for the own-family circle (Security M1).
--    Every existing edge was created through the admin-only routes, so the
--    constant default false is correct for them (metadata-only ADD COLUMN).
ALTER TABLE "person_relationships" ADD COLUMN "created_by_member" boolean DEFAULT false NOT NULL;--> statement-breakpoint
COMMENT ON COLUMN "person_relationships"."created_by_member" IS 'WP-4.0: true when a member created the edge together with a new person (relateTo). Counts for the own-family circle only while created_by_user_id also created one of its endpoints; admin edges (false) always count.';--> statement-breakpoint
-- 4. profiles: contacts (handles only, links are built server-side) and the
--    per-contact visibility map. show_email/show_phone/show_city stay the
--    source of truth for those fields; the map holds only the seven new kinds.
ALTER TABLE "profiles" ADD COLUMN "whatsapp" text;--> statement-breakpoint
ALTER TABLE "profiles" ADD COLUMN "instagram" text;--> statement-breakpoint
ALTER TABLE "profiles" ADD COLUMN "facebook" text;--> statement-breakpoint
ALTER TABLE "profiles" ADD COLUMN "tiktok" text;--> statement-breakpoint
ALTER TABLE "profiles" ADD COLUMN "linkedin" text;--> statement-breakpoint
ALTER TABLE "profiles" ADD COLUMN "github" text;--> statement-breakpoint
ALTER TABLE "profiles" ADD COLUMN "website" text;--> statement-breakpoint
ALTER TABLE "profiles" ADD COLUMN "contact_visibility" jsonb DEFAULT '{}'::jsonb NOT NULL;--> statement-breakpoint
COMMENT ON COLUMN "profiles"."contact_visibility" IS 'WP-4.0 per-contact visibility for whatsapp/instagram/facebook/tiktok/linkedin/github/website (missing key = hidden). Email/phone/city visibility stays in show_email/show_phone/show_city.';--> statement-breakpoint
ALTER TABLE "profiles" ADD CONSTRAINT "profiles_whatsapp_check" CHECK ("whatsapp" is null or (char_length("whatsapp") <= 16 and "whatsapp" ~ '^[+][1-9][0-9]{6,14}$')) NOT VALID;--> statement-breakpoint
ALTER TABLE "profiles" ADD CONSTRAINT "profiles_instagram_check" CHECK ("instagram" is null or (char_length("instagram") <= 30 and "instagram" ~ '^[A-Za-z0-9_](?:[A-Za-z0-9._]{0,28}[A-Za-z0-9_])?$')) NOT VALID;--> statement-breakpoint
ALTER TABLE "profiles" ADD CONSTRAINT "profiles_facebook_check" CHECK ("facebook" is null or (char_length("facebook") <= 50 and "facebook" ~ '^[A-Za-z0-9][A-Za-z0-9.]{4,49}$')) NOT VALID;--> statement-breakpoint
ALTER TABLE "profiles" ADD CONSTRAINT "profiles_tiktok_check" CHECK ("tiktok" is null or (char_length("tiktok") <= 24 and "tiktok" ~ '^[A-Za-z0-9_][A-Za-z0-9._]{0,22}[A-Za-z0-9_]$')) NOT VALID;--> statement-breakpoint
ALTER TABLE "profiles" ADD CONSTRAINT "profiles_linkedin_check" CHECK ("linkedin" is null or (char_length("linkedin") <= 100 and "linkedin" ~ '^[A-Za-z0-9][A-Za-z0-9-]{1,98}[A-Za-z0-9]$')) NOT VALID;--> statement-breakpoint
ALTER TABLE "profiles" ADD CONSTRAINT "profiles_github_check" CHECK ("github" is null or (char_length("github") <= 39 and "github" ~ '^[A-Za-z0-9](?:-?[A-Za-z0-9]){0,38}$')) NOT VALID;--> statement-breakpoint
ALTER TABLE "profiles" ADD CONSTRAINT "profiles_website_check" CHECK ("website" is null or (char_length("website") <= 200 and "website" ~ '^https://')) NOT VALID;--> statement-breakpoint
ALTER TABLE "profiles" ADD CONSTRAINT "profiles_contact_visibility_check" CHECK (jsonb_typeof("contact_visibility") = 'object' and ("contact_visibility" - array['whatsapp', 'instagram', 'facebook', 'tiktok', 'linkedin', 'github', 'website']::text[]) = '{}'::jsonb and not jsonb_path_exists("contact_visibility", '$.* ? (@.type() != "boolean")')) NOT VALID;--> statement-breakpoint
ALTER TABLE "profiles" VALIDATE CONSTRAINT "profiles_whatsapp_check";--> statement-breakpoint
ALTER TABLE "profiles" VALIDATE CONSTRAINT "profiles_instagram_check";--> statement-breakpoint
ALTER TABLE "profiles" VALIDATE CONSTRAINT "profiles_facebook_check";--> statement-breakpoint
ALTER TABLE "profiles" VALIDATE CONSTRAINT "profiles_tiktok_check";--> statement-breakpoint
ALTER TABLE "profiles" VALIDATE CONSTRAINT "profiles_linkedin_check";--> statement-breakpoint
ALTER TABLE "profiles" VALIDATE CONSTRAINT "profiles_github_check";--> statement-breakpoint
ALTER TABLE "profiles" VALIDATE CONSTRAINT "profiles_website_check";--> statement-breakpoint
ALTER TABLE "profiles" VALIDATE CONSTRAINT "profiles_contact_visibility_check";
