/**
 * Route inventory drift guard (WP-2.3) [SEC].
 *
 * Builds the real app with an `onRoute` recorder and fails when:
 * - a registered route is not classified in `ROUTE_MATRIX` (or vice versa),
 * - a route's `config.auth` / `requireVerifiedEmail` /
 *   `allowPendingPasswordChange` differs from its classification,
 * - a route omits `config.auth` (only the CORS preflight may),
 * - a HEAD route does not mirror its GET twin's guard config,
 * - `docs/security/routes.md` is stale. Regenerate it with
 *   `UPDATE_SECURITY_DOCS=1 pnpm --filter @cuencada/server test -- inventory`.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { afterAll, beforeAll, describe, expect, it, vi } from "vitest";
import type { App } from "../../app.js";
import { createTestApp } from "../../../test/helpers/app.js";
import { type RouteRecord, recordedRoutes } from "../../../test/helpers/routes.js";
import { type Expectation, expectationFor, PRINCIPALS, ROUTE_MATRIX, type RouteSpec, routeKey } from "./routeMatrix.js";

vi.mock("fastify", async (importOriginal) => {
  const actual = await importOriginal<typeof import("fastify")>();
  const { recordingFastify } = await import("../../../test/helpers/routes.js");
  const factory = recordingFastify(actual.default);
  return { ...actual, default: factory, fastify: factory };
});

const ROUTES_DOC = fileURLToPath(new URL("../../../../../docs/security/routes.md", import.meta.url));

/** Routes that may omit `config.auth` (registered by third-party plugins). */
const UNDECLARED_AUTH_ALLOWED = new Set(["OPTIONS *"]);

let app: App;
let routes: RouteRecord[];

beforeAll(async () => {
  recordedRoutes.length = 0;
  app = await createTestApp();
  routes = [...recordedRoutes];
});

afterAll(async () => {
  await app.close();
});

/** Registered routes without Fastify's automatic HEAD twins. */
function primaryRoutes(): RouteRecord[] {
  return routes.filter((route) => route.method !== "HEAD");
}

function classification(route: Pick<RouteRecord, "auth" | "requireVerifiedEmail" | "allowPendingPasswordChange">) {
  return {
    auth: route.auth ?? "user",
    requireVerifiedEmail: route.requireVerifiedEmail,
    allowPendingPasswordChange: route.allowPendingPasswordChange
  };
}

function specClassification(spec: RouteSpec) {
  return {
    auth: spec.auth,
    requireVerifiedEmail: spec.requireVerifiedEmail === true,
    allowPendingPasswordChange: spec.allowPendingPasswordChange === true
  };
}

const PRINCIPAL_HEADERS: Record<(typeof PRINCIPALS)[number], string> = {
  anonymous: "Anon",
  member: "Member",
  unverified: "Unverified",
  pending: "Pending pw",
  disabled: "Disabled",
  revoked: "Revoked",
  admin: "Admin"
};

function cell(spec: RouteSpec, principal: (typeof PRINCIPALS)[number]): string {
  if (spec.websocket === true) return "ticket";
  const expected = expectationFor(spec, principal);
  return expected === "2xx" ? "2xx" : String(expected.status);
}

function escapeCell(text: string): string {
  return text.replaceAll("|", "\\|");
}

/** Render `docs/security/routes.md` from the live inventory and the matrix. */
function renderRoutesDoc(): string {
  const specs = new Map(ROUTE_MATRIX.map((spec) => [routeKey(spec), spec]));
  const rows = primaryRoutes()
    .map((route) => ({ route, spec: specs.get(routeKey(route)) }))
    .sort((a, b) => a.route.url.localeCompare(b.route.url) || a.route.method.localeCompare(b.route.method));
  const header = [
    "Method",
    "Path",
    "auth",
    "Verified email",
    "Pending pw allowed",
    ...PRINCIPALS.map((principal) => PRINCIPAL_HEADERS[principal]),
    "Other member (IDOR)",
    "Scope / notes"
  ];
  const lines = [
    "# Route inventory",
    "",
    "<!-- Generated by apps/server/src/__tests__/security/inventory.test.ts; do not edit by hand. -->",
    "<!-- Regenerate: UPDATE_SECURITY_DOCS=1 pnpm --filter @cuencada/server test -- inventory -->",
    "",
    "Every route the API registers, with the guard configuration it declares",
    "(`config.auth`, `requireVerifiedEmail`, `allowPendingPasswordChange`) and the",
    "status class each principal gets in `authz-matrix.test.ts`. Fastify's automatic",
    "HEAD twins of GET routes are omitted; the inventory test checks they carry the",
    "same guard config. `401`/`403` cells are guard denials (`UNAUTHENTICATED`,",
    "`PASSWORD_CHANGE_REQUIRED`, `FORBIDDEN`, `EMAIL_UNVERIFIED`); other non-2xx",
    "cells are handler answers for that principal's own data.",
    "",
    `Total: ${rows.length} routes (${rows.filter((row) => row.route.auth === "public").length} public, ` +
      `${rows.filter((row) => (row.route.auth ?? "user") === "user").length} user, ` +
      `${rows.filter((row) => row.route.auth === "admin").length} admin, ` +
      `${rows.filter((row) => row.route.auth === "cookie").length} cookie).`,
    "",
    `| ${header.join(" | ")} |`,
    `| ${header.map(() => "---").join(" | ")} |`
  ];
  for (const { route, spec } of rows) {
    if (spec === undefined) continue;
    const status = (expected: Expectation): string => (expected === "2xx" ? "2xx" : String(expected.status));
    const probes = spec.probes ?? [];
    const idor = [...new Set(probes.filter((probe) => probe.kind === "idor").map((probe) => status(probe.expect)))].join(", ");
    const otherProbes = probes
      .filter((probe) => probe.kind !== "idor")
      .map((probe) => `${probe.kind === "mass-assignment" ? "mass assignment" : "probe"}: ${probe.label} → ${status(probe.expect)}`);
    const notes = [spec.owner, spec.note, ...otherProbes].filter((text): text is string => text !== undefined).join("; ");
    lines.push(
      `| ${[
        route.method,
        `\`${route.url}\``,
        route.auth ?? "(default user)",
        route.requireVerifiedEmail ? "yes" : "",
        route.allowPendingPasswordChange ? "yes" : "",
        ...PRINCIPALS.map((principal) => cell(spec, principal)),
        idor,
        escapeCell(notes)
      ].join(" | ")} |`
    );
  }
  return `${lines.join("\n")}\n`;
}

describe("route inventory", () => {
  it("records the routes the app registers", () => {
    expect(primaryRoutes().length).toBeGreaterThan(90);
  });

  it("classifies every registered route in the authorization matrix, and nothing else", () => {
    const registered = new Set(primaryRoutes().map(routeKey));
    const classified = new Set(ROUTE_MATRIX.map(routeKey));
    expect(
      { unclassified: [...registered].filter((key) => !classified.has(key)) },
      "Unclassified route: add it to ROUTE_MATRIX in apps/server/src/__tests__/security/routeMatrix.ts " +
        "(auth level + a minimal valid request), then regenerate docs/security/routes.md with " +
        "UPDATE_SECURITY_DOCS=1 pnpm --filter @cuencada/server test -- inventory"
    ).toEqual({ unclassified: [] });
    expect({ stale: [...classified].filter((key) => !registered.has(key)) }).toEqual({ stale: [] });
    expect(ROUTE_MATRIX.length).toBe(classified.size);
  });

  it("matches each route's guard config to its classification", () => {
    const specs = new Map(ROUTE_MATRIX.map((spec) => [routeKey(spec), spec]));
    const mismatches = primaryRoutes().flatMap((route) => {
      const spec = specs.get(routeKey(route));
      if (spec === undefined) return [];
      const actual = classification(route);
      const expected = specClassification(spec);
      return JSON.stringify(actual) === JSON.stringify(expected)
        ? []
        : [`${routeKey(route)}: registered ${JSON.stringify(actual)}, classified ${JSON.stringify(expected)}`];
    });
    expect(mismatches).toEqual([]);
  });

  it("requires every route to declare config.auth explicitly", () => {
    const undeclared = primaryRoutes()
      .filter((route) => route.auth === null)
      .map(routeKey)
      .filter((key) => !UNDECLARED_AUTH_ALLOWED.has(key));
    expect(undeclared).toEqual([]);
  });

  it("gives every HEAD route the same guard config as its GET twin", () => {
    const gets = new Map(routes.filter((route) => route.method === "GET").map((route) => [route.url, route]));
    const problems = routes
      .filter((route) => route.method === "HEAD")
      .flatMap((head) => {
        const get = gets.get(head.url);
        if (get === undefined) return [`HEAD ${head.url} has no GET twin`];
        return JSON.stringify(classification(head)) === JSON.stringify(classification(get))
          ? []
          : [`HEAD ${head.url} differs from GET`];
      });
    expect(problems).toEqual([]);
  });

  it("only uses the chat route for WebSockets", () => {
    expect(routes.filter((route) => route.websocket).map((route) => route.url)).toEqual(["/api/chat/ws", "/api/chat/ws"]);
  });

  it("keeps docs/security/routes.md in sync with the inventory", () => {
    const rendered = renderRoutesDoc();
    if (process.env.UPDATE_SECURITY_DOCS === "1") writeFileSync(ROUTES_DOC, rendered);
    let committed = "";
    try {
      committed = readFileSync(ROUTES_DOC, "utf8");
    } catch {
      committed = "";
    }
    expect(committed, "docs/security/routes.md is stale: rerun with UPDATE_SECURITY_DOCS=1").toBe(rendered);
  });
});
